### ISSUE TITLE
MCP2517FD Driver for Pi 3B+

### ISSUE THREAD

**Issue by Dave-uk2018** [GBert/misc#5]
Does the driver work on the new Raspberry Pi 3B+ ?

**Comment by Mimi6257** [comment]
I installed this driver on my raspberry pi 3, the installation is ok.
But after a few moment of using it, everything freeze and the CPU goes to 100 % and I ve got an high temperatur on the PCB !

What about you, did you try to install it ?

**Comment by GBert** [comment]
please contact msperl
