### ISSUE TITLE
Doesn't work en RaspberryPi 3

### ISSUE THREAD

**Issue by Mimi6257** [GBert/misc#6]
Hi, 

I installed this driver on my raspberry pi 3, the installation is ok.
But after a few moment of using it, everything freeze and the CPU goes to 100 % and I ve got an high temperatur on the PCB !

See below for the entire description of my problem

Thanks.

=============================================================

Configuration : 
- Raspberry PI 3 Model B Rev 1.2
- can module PICAN FD skpang Rev B 10/17

Connected to my laptop with USB PEAK PCAN FD and I check the traffic with PCan-View

This is the EOF of config.txt : 

```
dtparam=spi=on
core_freq=250
kernel=ms7/zImage
device_tree=ms7/bcm2710-rpi-3-b.dtb
overlay_prefix=ms7/overlays/
dtoverlay=mcp2517fd-can0
dtparam=interrupt=25
dtparam=oscillator=40000000
dtparam=spimaxfrequency=20000000
```
First I start up the can0 with : 
`sudo ip link set can0 up type can bitrate 250000 dbitrate 2000000 fd on sample-point .8 dsample-point .8`

In another consol, I check the can traffic with :
`candump can0`

All traffic from my laptop to the raspberry works fine ( normal CAN, CAN FD, CAN FD BRS) : 
```
pi@raspberrypi:~ $ candump can0
  can0  007DFEAC   [8]  01 02 03 04 05 06 07 08
  can0  007DFEAC   [8]  01 02 03 04 05 06 07 08
  can0  007DFEAC  [08]  08 06 04 02 07 05 03 01
  can0  007DFEAC  [08]  08 06 04 02 07 05 03 01
  can0  007DFEAC  [08]  09 09 09 09 05 05 05 05
  can0  007DFEAC  [08]  09 09 09 09 05 05 05 05
```

But when I want to send from the raspberry to my laptop, everything works fine with normal CAN and CAN FD, but If I send a message in CAN FD with Bite Rate Switch, every things goes wrong.
There are the commands I use : 
normal CAN : `cansend can0 7DF#0301050000000000`
CAN FD : `cansend can0 7DF##05555555555555555`
For now , everything is OK
CAN FD BRS : `cansend can0 7DF##15555555555555555`
And now, this is what I have in the candump : 
```
  can0       00C   [8]  00 00 00 00 08 00 00 00
  can0       00C   [8]  00 00 00 00 08 00 00 00
  can0       08C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       00C   [8]  00 00 00 00 20 00 00 00
  can0       0C8   [8]  00 00 00 00 00 00 00 00
```
I have to set down the can0 to stop it.
After I start it up again, and here, after a few command of normal CAN or CAN FD (about 3 or 4), the raspberry freeze and nothing is possible, I can't set down the can0, I even can't shutdown the raspberry. The CPU goes to 100 %, the temperature increase, I have no choice to disconnect the power of the raspberry.

**Comment by msperl** [comment]
The 00C messages indicate Bus error messages emitted by the can driver.

Even though the messages are submitted "correctly" as error frames (as far as I can tell) they seem to show up as "normal" can frames...

Such messages typically indicates CAN Bus errors - e.g timing issues especially with CANFD and clock switching.

Automatic computation of CAN FD parameters is very sensitive and may not be optimal on linux as of now - the "correct" values for dtq, dprop-seg, dphase-seg1 and dphase-seg2 need to get used which need to be matching on all members of the CAN bus.

A description of the error IDs can be found here:
https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/can/error.h#L51
so 00C would describe: controller error and protocol violation

Please try without separate clock speeds for data  on both sides and see if it works then.

I did dig into some emails to find some values for dtq et.al.:

For 2MHz (and 4MHz or 40MHz crystal) I believe the following may be "correct":
```dtq 25 dprop-seg 10 dphase-seg1 5 dphase-seg2 4 dsjw 3```

I heard that interrupts are running continuously while CAN bus is not connected, so this may be related.

I am currently rewriting the driver for inclusion into the kernel, but it may take some more time getting it right...

**Comment by GBert** [comment]
waiting for new driver from msperl
