### ISSUE TITLE
pickle: stops execution if piped

### ISSUE THREAD

**Issue by baboco** [GBert/misc#7]
# Issue
When redirecting pickle's output, it stops execution before finishing.
# Example
When calling `p24 select dsPIC33EP256MC206 lvp flash 128` everything works as expected.  
When calling `p24 select dsPIC33EP256MC206 lvp flash 128 > output.txt`, the last reset sequence gets cut to a point the controller does not recover from the read status and will not start afterwards. 
This also happens when calling `c=$(p24…)` or `p24 … | grep 000000`  

Connecting to an oscilloscope shows three reset signals. 
While the first two (in my setup) are pulled down to 0.7V, the last one only gets to 2V, the other two signals also abort early and default to high.
![defect](https://user-images.githubusercontent.com/34479226/46350970-6ba0fd80-c656-11e8-80ad-42a100d426d1.png)

When running pickle on its own, the last signal is clear:
![clear](https://user-images.githubusercontent.com/34479226/46351002-87a49f00-c656-11e8-887e-b0ad12423b35.png)

Any workarounds are appreciated :)

**Comment by GBert** [comment]
AFAIK fixed
