### ISSUE TITLE
[stm32-slcan] USB and CAN cannot be used simultaneously

### ISSUE THREAD

**Issue by skoehler** [GBert/misc#9]
Hi, can you elaborate why USB and CAN cannot be used simultaneously? I can certainly configure it this way in STM32CubeIDE/CubeMX. So pin-wise, there is no limitation. Please elaborate.

**Comment by GBert** [comment]
RM0008   page 629

In low, medium-, high- and XL-density devices the USB and CAN share a dedicated 512-byte SRAM memory for data transmission and reception, and so they cannot be used concurrently (the shared SRAM is accessed through CAN and USB exclusively). The USB and CAN can be used in the same application but not at the same time.

**Comment by skoehler** [comment]
Thanks for the information about the STM32F103. That is very disappointing. I'd like to record all packets on a CAN bus running at maximum rate (1MHz). I'm pretty sure typical UART baud rates wont do.

There are STM32F407 development board on AliExpress for less than 8€. It doesn't seem to have the USB/CAN bus restriction. I have one of those and I will probably try to port STM32-SLCAN to that device.

**Comment by GBert** [comment]
To be honest the UART speed should be twice the CAN Baud speed. So 1MHz UART is to slow for a full saturated 1MBaud CAN bus.

This project might be better fit for you purpose:
https://www.mikrocontroller.net/articles/BusAnalyzer

or just use a RPi:
https://github.com/GBert/misc/blob/master/RPi-MCP2515/README.md

or BPi:
http://lnxpps.de/bpie/
